### ISSUE TITLE
Subsumption Architecture

### ISSUE THREAD

**Issue by sana911** [MihirSPatil/-Rapid-prototyping-mobile-robot-platform-for-warehouse-logistics#2]
What do you make of this? @MihirSPatil 

http://answers.ros.org/question/172499/ros-process-in-subsumption-architecture/
http://answers.ros.org/question/43537/turning-ros-nodes-on-and-off-subsumption-style/

Is this **feasible?**

**Comment by MihirSPatil** [comment]
Doesn't look so

**Comment by UthejD** [comment]
though we can use multiplexers for switching an prioritizing it is not feasible as a lot of CPU cycles will be wasted even if the node is just idling. Since there is currently no way of solving this problem I think we should look at the other architectures.
